apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
        - name: app
          image: dimazhornyk/node-app:1.0
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            failureThreshold: 1
            periodSeconds: 10
        - name: nginx
          image: nginx:1.15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx